---
name: 'kbb1-64x6'
gpu: 0

dataset:
  num_samples: 70 
  train_ratio: 0.95
  skip: 16
  input: '/home/zat/leela-chess/build/data-*/*'
  path: '/home/zat/leela-chess/build/'

training:
  batch_size: 2048
  learning_rate: 0.1
  decay_rate: 0.1
  decay_step: 200000
  policy_loss_weight: 1.0
  value_loss_weight: 0.01
  path: '/home/zat/leela-chess/networks'

model:
  filters: 64
  residual_blocks: 6
...
